import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <nav className="p-4 bg-slate-900 text-white flex gap-4">
            <a href="/" className="hover:text-slate-300">Home</a>
            <a href="/benchmark" className="hover:text-slate-300">Benchmark</a>
            <a href="/history" className="hover:text-slate-300">History</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
