"""create_tables

Revision ID: c201b4e3c9b1
Revises: 8158836069a8
Create Date: 2026-09-05 12:27:22.477541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'c201b4e3c9b1'
down_revision: Union[str, Sequence[str], None] = '8158836069a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('answer_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_run_id'), 'answers', ['run_id'], unique=False)
    op.create_table('evidence_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_type', sa.Enum('claim', 'measurement', 'region', 'mask', 'model', 'input', name='nodetype'), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('parent_node_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_node_id'], ['evidence_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_nodes_run_id'), 'evidence_nodes', ['run_id'], unique=False)
    op.create_table('evidence_packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('package_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_packages_run_id'), 'evidence_packages', ['run_id'], unique=False)
    op.create_table('execution_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameter_overrides_json', sa.JSON(), nullable=True),
    sa.Column('rerun_stage_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_parent_run_id'), 'experiments', ['parent_run_id'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('class_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_mask_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regions_run_id'), 'regions', ['run_id'], unique=False)
    op.create_table('execution_traces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('trace_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['execution_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('evidence_node_id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.Enum('accepted', 'rejected', 'needs_review', name='feedbacktagenum'), nullable=False),
    sa.Column('reviewer_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_node_id'], ['evidence_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('input_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('profile_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('input_profiles')
    op.drop_table('feedback_tags')
    op.drop_table('execution_traces')
    op.drop_index(op.f('ix_regions_run_id'), table_name='regions')
    op.drop_index('idx_regions_geometry', table_name='regions', postgresql_using='gist')
    op.drop_table('regions')
    op.drop_table('images')
    op.drop_index(op.f('ix_experiments_parent_run_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_table('execution_plans')
    op.drop_index(op.f('ix_evidence_packages_run_id'), table_name='evidence_packages')
    op.drop_table('evidence_packages')
    op.drop_index(op.f('ix_evidence_nodes_run_id'), table_name='evidence_nodes')
    op.drop_table('evidence_nodes')
    op.drop_index(op.f('ix_answers_run_id'), table_name='answers')
    op.drop_table('answers')
    # ### end Alembic commands ###
